{% set name = "ld1" %}
{% set version = "6.3MaX" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/QEF/q-e/-/archive/qe-{{ version }}/q-e-qe-{{ version }}.tar.gz
  sha256: 9e130a8042b244964f4b7b04ef3a694f610610d166ae809c4a045aa603633688

build:
  skip: true  # [not linux]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - make
    - m4
    - wget
  host:
    - libblas
    - libcblas
    - liblapack
    - liblapacke
    - fftw
    - libxc ==4.3.*
  run:
    - fftw

test:
  commands:
    - test -f ${PREFIX}/bin/ld1.x

about:
  home: http://www.quantum-espresso.org
  license: GPL-2.0-only
  license_family: GPL
  license_file: License
  summary: QUANTUM ESPRESSO (opEn-Source Package for Research in Electronic Structure, Simulation, and Optimization)

  description: |
    ld1 is the atomic codo of QUANTUM ESPRESSO an integrated suite of Open-Source computer 
    codes for electronic-structure calculations and materials modeling 
    at the nanoscale. It is based on density-functional theory, plane 
    waves, and pseudopotentials.
  doc_url: http://www.quantum-espresso.org/Doc/user_guide/
  dev_url: https://github.com/QEF/q-e

extra:
  recipe-maintainers:
    - unkcpz
